### ISSUE TITLE
ISO download failed

### ISSUE THREAD

**Issue by 0x43434343** [francisck/DanderSpritz_lab#3]
==> Target: ISO download failed.
Build 'Target' errored: ISO download failed.
    DanderSpritz-box: Error downloading: 502 Bad Gateway
==> DanderSpritz-box: ISO download failed.
Build 'DanderSpritz-box' errored: ISO download failed.

**Comment by netadr** [comment]
Use `wget` to manually download the ISOs found in the JSON files and change the `iso_url` string to the local path of the ISOs.

**Comment by jekil** [comment]
It is not matter of reply or what.. Microsoft just removed windows 7 images from windows 10 release.

**Comment by woj-ciech** [comment]
Hey, any update on this?

**Comment by francisck** [comment]
Apologies for the delay replying here.

as @jekil mentioned, it looks like Microsoft has removed the ISOs this relied one.

The packer files were modified from the following project:

https://github.com/joefitzgerald/packer-windows

I am actively looking for new ISO urls and have reached out to a friend at MS to see if there is a better way to do this in the future.

**Comment by woj-ciech** [comment]
Thanks for still keeping this project alive. If you would find some Windows ISO I can offer my help and prepare OVA images with configuration included.

**Comment by jekil** [comment]
Why not using VM ready from Microsoft?
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by bluesentinelsec** [comment]
Any chance we can get a version with updated downloads?

**Comment by francisck** [comment]
Hello all - I apologize sincerely for the delay in getting this issue resolved. Working at a start up has taken all of my time and it was difficult to find the time to work on this - although it's a project near and  dear to my heart.

I've look at the recent updates on the packer for windows repo linked above and have grabbed the latest available link for Windows 10. I have validated that this is working on my end with the latest commits to this repo (https://github.com/francisck/DanderSpritz_lab/commit/428a31662890a3aba3fe2435c14242a5ce343940)

> Why not using VM ready from Microsoft?
> https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

My understanding is that Microsoft makes those VMs difficult to programmatically download on purpose, since you are not supposed to be redistributing them. I'll keep an eye out to see if we run into problems again and see what steps we should take. I've also backed up all of the ISOs used so I can host them myself in the future just in case.

Thank you all for your patience.
